spring.application.name=wcharge-network-backend

spring.datasource.url=jdbc:h2:mem:chargedb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=charge
spring.datasource.password=

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

security.jwt.secret-key=pKjigF8okF9SHues7QYHedx85X3Fo9595h3rMP6P5Jk